export const SKILLS = [
  { key: 'appraise', label: 'Appraise', mod: 'int', featIndex: 2, itemIndex: 8 },
  { key: 'balance', label: 'Balance', mod: 'dex', featIndex: 3, itemIndex: 9, armorPenalty: 1 },
  { key: 'bluff', label: 'Bluff', mod: 'cha', featIndex: 4, itemIndex: 10 },
  { key: 'climb', label: 'Climb', mod: 'str', featIndex: 5, itemIndex: 11, armorPenalty: 1 },
  { key: 'concentration', label: 'Concentration', mod: 'con', featIndex: 6, itemIndex: 12 },
  { key: 'decipherScript', label: 'Decipher Script', mod: 'int', featIndex: 7, itemIndex: 13 },
  { key: 'diplomacy', label: 'Diplomacy', mod: 'cha', featIndex: 8, itemIndex: 14 },
  { key: 'disableDevice', label: 'Disable Device', mod: 'int', featIndex: 9, itemIndex: 15 },
  { key: 'disguise', label: 'Disguise', mod: 'cha', featIndex: 10, itemIndex: 16 },
  { key: 'escapeArtist', label: 'Escape Artist', mod: 'dex', featIndex: 11, itemIndex: 17, armorPenalty: 1 },
  { key: 'forgery', label: 'Forgery', mod: 'int', featIndex: 12, itemIndex: 18 },
  { key: 'gatherInfo', label: 'Gather Info', mod: 'cha', featIndex: 13, itemIndex: 19 },
  { key: 'handleAnimal', label: 'Handle Animal', mod: 'cha', featIndex: 14, itemIndex: 20 },
  { key: 'heal', label: 'Heal', mod: 'wis', featIndex: 15, itemIndex: 21 },
  { key: 'hide', label: 'Hide', mod: 'dex', featIndex: 16, itemIndex: 22, armorPenalty: 1 },
  { key: 'intimidate', label: 'Intimidate', mod: 'cha', featIndex: 17, itemIndex: 23 },
  { key: 'jump', label: 'Jump', mod: 'str', featIndex: 18, itemIndex: 24, armorPenalty: 1 },
  { key: 'listen', label: 'Listen', mod: 'wis', featIndex: 19, itemIndex: 25 },
  { key: 'moveSilently', label: 'Move Silently', mod: 'dex', featIndex: 20, itemIndex: 26, armorPenalty: 1 },
  { key: 'openLock', label: 'Open Lock', mod: 'dex', featIndex: 21, itemIndex: 27 },
  { key: 'ride', label: 'Ride', mod: 'dex', featIndex: 22, itemIndex: 28 },
  { key: 'search', label: 'Search', mod: 'int', featIndex: 23, itemIndex: 29 },
  { key: 'senseMotive', label: 'Sense Motive', mod: 'wis', featIndex: 24, itemIndex: 30 },
  { key: 'sleightOfHand', label: 'Sleight of Hand', mod: 'dex', featIndex: 25, itemIndex: 31, armorPenalty: 1 },
  { key: 'spot', label: 'Spot', mod: 'wis', featIndex: 26, itemIndex: 32 },
  { key: 'survival', label: 'Survival', mod: 'wis', featIndex: 27, itemIndex: 33 },
  { key: 'swim', label: 'Swim', mod: 'str', featIndex: 28, itemIndex: 34, armorPenalty: 2 },
  { key: 'tumble', label: 'Tumble', mod: 'dex', featIndex: 29, itemIndex: 35 },
  { key: 'useTech', label: 'Use Tech', mod: 'int', featIndex: 30, itemIndex: 36 },
  { key: 'useRope', label: 'Use Rope', mod: 'dex', featIndex: 31, itemIndex: 37 },
];

export default SKILLS;
